main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('accounts/signup/', views.signup, name='signup'),
  path('health/', views.health_index, name='health_index'),
  path('health/<int:health_id>/', views.health_detail, name='health_detail'),
  path('health/create/', views.HealthCreate.as_view(), name='health_create'),
  path('health/<int:pk>/update/', views.HealthUpdate.as_view(), name='health_update'),
  path('health/anonymous/', views.anonymous, name='anonymous'),
  path('entry/', views.entry_index, name='entry_index'),
  path('entry/<int:entry_id>/', views.entry_detail, name='detail'),
  path('entry/create/', views.FormCreate.as_view(), name='form_create'),
  path('entry/<int:pk>/update/', views.EntryUpdate.as_view(), name='entry_update'),
  path('entry/<int:pk>/delete/', views.EntryDelete.as_view(), name='entry_delete'),
  path('entry/<int:entry_id>/add_partner/', views.add_partner, name='add_partner'),
  path('<int:entry_id>/delete/', views.delete_partner, name='delete_partner'),
  # Pick a Location with an Entry(M:M)
  path('entry/<int:entry_id>/picked_location/<int:location_id>/', views.picked_location, name='picked_location'),
  # Unpick a location 
  path('entry/<int:entry_id>/location_unpicked/<int:location_id>/', views.unpicked_location, name='unpicked_location'),
  path('location/', views.LocationList.as_view(), name='location_index'),
  path('location/<int:pk>/', views.LocationDetail.as_view(), name='location_detail'),
  path('location/create/', views.LocationCreate.as_view(), name='location_create'),
  
  path('location/<int:pk>/update/', views.LocationUpdate.as_view(), name='location_update'),
  path('location/<int:pk>/delete/', views.LocationDelete.as_view(), name='location_delete'),


]



#  path('entry/<int:entry_id>/add_partner/', views.add_partner, name='add_partner'),

tracker19/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
     path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
# Create your models here.
from django.db import models
from django.urls import reverse

from datetime import datetime
from django.contrib.auth.models import User
from django import forms
from django.utils.safestring import mark_safe

HealthStatus= (
    ('choice1', 'I’ve been dignoised with COVID-19 and would like to create a record of my whereabouts'), 
    ('choice2','I’ve recovered from COVID-19, but would like to track my whereabouts'), 
    ('choice3','I’ve not been tested for COVID-19, but feel sick and want to track my whereabouts'), 
    ('choice4','I do not have COVID-19 but would like to track my whereabout') 
)

Feeling = (
    ('choice1', mark_safe('&#128524;')),
    ('choice1', mark_safe('&#128577;')),
    ('choice1', mark_safe('&#128555;')),
    ('choice1', mark_safe('&#128567;')),
)


class Location (models.Model) : 
    name = models.CharField(max_length=100)
        #Shoppers, Metro... etc
    address = models.CharField(max_length=250)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('location_detail', kwargs={'pk': self.id})
    
    class Meta:
        ordering = ['-name']

class Entry (models.Model) : 
    date = models.DateField()
    time = models.TimeField()    
    comments = models.CharField(max_length=250)
    location = models.ManyToManyField(Location)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.location

class Partner(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('entry_detail', kwargs={'pk': self.id})

    class Meta:
        ordering = ['-name']

class Health(models.Model):
    date = models.DateField()
    health = models.CharField('Which option best describes your health status',choices= HealthStatus, max_length=100)
    feeling = models.CharField('How do you feel today ?',  choices= Feeling, max_length=100)
    symptoms = models.CharField('What are your current symptoms ?', max_length=250)
    comments = models.CharField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_feeling_display()}"
    
    def get_absolute_url(self):
        return reverse('health_detail', kwargs={'health_id': self.id})

main_app/forms.py
from django import forms
from .models import Entry, Partner, Location, Health 
from django.forms import ModelForm

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class EntryForm(ModelForm):
    class Meta:
        model = Entry
        fields = [ 'date', 'time', 'comments' ]
        widgets = {
            'date': DateInput(),
            'time': TimeInput()
        }


class HealthForm(ModelForm):
    class Meta:
        model = Health 
        fields = ['date', 'health', 'feeling', 'symptoms', 'comments']
        widgets = {
            'date': DateInput(),
        }

class PartnerForm(ModelForm):
    class Meta:
        model = Partner
        fields = ['name', 'description']


class LocationForm(ModelForm):
    class Meta:
        model = Location
        fields = ['name', 'address']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.http import HttpResponse
from .models import Entry, Partner, Location,Health
from .forms import EntryForm, HealthForm, PartnerForm



#Classes go here

class FormCreate(LoginRequiredMixin,CreateView):
  model = Entry
  form_class = EntryForm
  success_url = '/entry/'

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class EntryUpdate(LoginRequiredMixin,UpdateView):
  model = Entry
  fields = ['comments' ]
  success_url = '/entry/'

class EntryDelete(LoginRequiredMixin,DeleteView):
  model = Entry
  success_url = '/entry/'
class LocationList(ListView):
  model = Location

class LocationDetail(DetailView):
  model = Location


class LocationCreate(CreateView):
  model = Location
  fields = '__all__'

class HealthCreate(LoginRequiredMixin,CreateView):
  model = Health
  form_class = HealthForm 
  success_url = '/health/'

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class HealthUpdate(LoginRequiredMixin,UpdateView):
  model = Health
  fields = ['date', 'health', 'feeling', 'symptoms', 'comments' ]
  success_url = '/health/'

@login_required 
def health_index(request):
  health = Health.objects.filter(user=request.user)
  return render(request, 'health/index.html', { 'health': health })


@login_required 
def health_detail(request, health_id):
  health = Health.objects.get(id=health_id)
  return render(request, 'health/detail.html', {
    'health': health
  })
  
def anonymous(request): 
    return render(request, 'anonymous/anonymous.html')


class LocationUpdate(UpdateView):
  model = Location
  fields = ['name', 'address', 'latitude', 'longitude']

class LocationDelete(DeleteView):
  model = Location
  success_url = '/location/'

# Create your views here.
def home(request): 
    return render(request, 'home/home.html')

def about(request): #Static, read
  return render(request, 'about/about.html')

def signup(request):
  error_message = ''
  if request.method == 'POST': 
    form = UserCreationForm(request.POST)
    if form.is_valid(): 
      user = form.save()
      login(request,user)
      return redirect('anonymous')
    else: 
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


@login_required 
def entry_index(request):
  entry = Entry.objects.filter(user=request.user)
  return render(request, 'entry/index.html', { 'entry': entry })

@login_required 
def entry_detail(request, entry_id):
  entry = Entry.objects.get(id=entry_id)
  partner_form = PartnerForm()
  no_location = Location.objects.exclude(id__in = entry.location.all().values_list('id'))
  return render(request, 'entry/detail.html', {
    'entry': entry,
    'partner_form': partner_form,
    'locations': no_location
  })

def picked_location(request, entry_id, location_id):
  Entry.objects.get(id=entry_id).location.add(location_id)
  return redirect('detail', entry_id=entry_id)

@login_required 
def entry_index(request):
  entry = Entry.objects.filter(user=request.user)
  return render(request, 'entry/index.html', { 'entry': entry })

def unpicked_location(request, entry_id, location_id):
  Entry.objects.get(id=entry_id).location.remove(location_id)
  return redirect('detail', entry_id=entry_id)

@login_required
def add_partner(request, entry_id):
  partner_form = PartnerForm(request.POST)
  if partner_form.is_valid():
    new_partner = partner_form.save(commit=False)
    new_partner.entry_id = entry_id
    new_partner.save()
    return redirect('detail', entry_id = entry_id)

@login_required
def delete_partner(request, entry_id):
    Partner.objects.filter(id=entry_id).delete()
    return redirect('detail', entry_id = entry_id)

main_app/templates/entry/detail.html
{% extends 'base.html' %}
{% block content %}

<main class="container">

  <h1>Entry Details</h1>
  <div class="row">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ entry.date }}</span>

        <p>Time: {{ entry.time }}</p>
        <p>Comments: {{ entry.comments }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'entry_update' entry.id %}">Edit</a>
        <a href="{% url 'entry_delete' entry.id %}">Delete</a>
      </div>
    </div>


    <hr>

    <div class="row">
      <div class="col s6">
        <h3>Locations</h3>
        {% if entry.location.count %}
        {% for location in entry.location.all %}
            <div class="card">
              <div class="card-content">
                <span class="card-title">
                  {{ location.name }}
                  <p> {{ location.address }}</p>
                </span>
              </div>
              <div class="card-action">
                <form action="{% url 'unpicked_location' entry.id location.id %}" method="post">
                    {% csrf_token %}
                  <button type="submit" class="btn">Remove</button>
                </form>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <h5>Pick a location</h5>
        {% endif %}
      </div>  
    
    
      <!-- Available locations will come after this line -->
    
      <div class="col s6">
        <h3>Available Locations</h3>
        {% if locations.count %}
        {% for location in locations.all %}
            <div class="card">
              <div class="card-content">
                <span class="card-title">
                  {{ location.name }}
                  <p> {{ location.address }}</p>
                </span>
              </div>
              <div class="card-action">
                <form action="{% url 'picked_location' entry.id location.id %}" method="post">
                    {% csrf_token %}
                  <button type="submit" class="btn">Add</button>
                </form>
              </div>
            </div>
          {% endfor %}
        {% endif %}
      </div>
    </div> 


    <hr>
    <div class="col s6">
      <h3>Add a Travel Partner</h3>
      <form action="{% url 'add_partner' entry.id %}" method="post">
        {% csrf_token %}
        {{ partner_form.as_p }}
        <input type="submit" class="btn" value="Add Travel Partner">
      </form>
      <table id="striped">
        <thead>
          <tr>
            <th>Travel Partner</th>
            <th>Description</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for partner in entry.partner_set.all %}
          <tr>
            <td>{{ partner.name }}</td>
            <td>{{ partner.description }}</td>
            <td><a href="{% url 'delete_partner' entry.id %}">X</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>
{% endblock %}

main_app/templates/entry/index.html
{% extends 'base.html' %}
{% block content %}
<main class="container">
<h1>Entries</h1>

<a href="{% url 'form_create'%}">
  <div class="card">
      <div class="card-content">
          <p>Add an Entry</p>
      </div>
  </div>
</a>


{% for entry in entry %}
  <a href="{% url 'detail' entry.id %}" >
    <div class="card">
        <div class="card-content">
            <p>Date: {{ entry.date }}</p>
            <p>Time: {{ entry.time }}</p>
            <p>Comments: {{ entry.comments }}</p>  
        </div>
    </div>
  </a>
{% endfor %}
</main>
{% endblock %}